name: spatial-cells-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8, <3.11
  - ipykernel
  - matplotlib>=3.7.0
  - pandas>=2.0.3
  - seaborn>=0.12.2
  - shapely>=2.0
  - tqdm
  - pip
  - pip:
      - anndata==0.9.2
      - scanpy==1.9.4
      