name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master, gh-pages] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/